import { supabase } from '@/lib/supabase'
import { getUserDisplayName } from '@/utils/userDisplayName'
export const ACTIVITY_CREATED_EVENT = 'sigma:activity-created'

// The RPC records the authenticated actor and database timestamp server-side.
// Logging errors are deliberately surfaced: silently losing an audit event
// would make a successful administrative change unauditable.
export async function logActivity(action: string, entityType: string, description: string, entityId?: string) {
  const rpcResult = await (supabase as any).rpc('record_activity', {
    p_action: action,
    p_entity_type: entityType,
    p_description: description,
    p_entity_id: entityId ?? null,
  })

  if (rpcResult.error) {
    // Compatibility path for projects where PostgREST has not refreshed the
    // RPC schema yet. This remains an authenticated, persistent database
    // insert and created_at is still generated by PostgreSQL's now().
    const { data: authData, error: authError } = await supabase.auth.getUser()
    const user = authData.user
    if (authError || !user) {
      throw new Error(`The change succeeded, but its activity log could not be saved: ${rpcResult.error.message}; ${authError?.message ?? 'no authenticated user'}`)
    }

    let recentQuery = (supabase as any)
      .from('activity_logs')
      .select('id')
      .eq('actor_id', user.id)
      .eq('action', action)
      .eq('entity_type', entityType)
      .gte('created_at', new Date(Date.now() - 15_000).toISOString())
      .order('created_at', { ascending: false })
      .limit(1)
    recentQuery = entityId ? recentQuery.eq('entity_id', entityId) : recentQuery.is('entity_id', null)
    const recentResult = await recentQuery.maybeSingle()

    if (!recentResult.error && recentResult.data) {
      window.dispatchEvent(new CustomEvent(ACTIVITY_CREATED_EVENT))
      return
    }

    const directResult = await (supabase as any)
      .from('activity_logs')
      .insert({
        actor_id: user.id,
        actor_name: getUserDisplayName(user, 'Admin'),
        actor_email: user.email ?? null,
        actor_role: 'Admin',
        action,
        entity_type: entityType,
        entity_id: entityId ?? null,
        description,
      })
      .select('id, created_at')
      .single()

    if (directResult.error || !directResult.data) {
      throw new Error(
        `The change succeeded, but its activity log could not be saved. RPC: ${rpcResult.error.message}. Insert: ${directResult.error?.message ?? 'no row returned'}`
      )
    }
  }

  window.dispatchEvent(new CustomEvent(ACTIVITY_CREATED_EVENT))
}
